version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[github-actions] "
      prefix: "[github-actions] "
    labels:
      - "github-actions"
      - "dependencies"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "master"
    versioning-strategy: increase
    schedule:
      interval: "monthly"
    commit-message:
      # Prefix all commit messages with "[composer] "
      prefix: "[composer] "
    labels:
      - "npm"
      - "dependencies"
